Test.UI/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Test.Model;
using Test.BLL;
using System.Dynamic;
using Test.UI.Common;

namespace Test.UI.Controllers
{
    public class LoginController : Controller
    {
        LoginBll loginBll = new LoginBll();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Login()
        {
            var actionResult = default(ActionResult);

            Login inModel = new Login();
            this.UpdateModel<Login>(inModel);

            #region 参数验证
            if (string.IsNullOrEmpty(inModel.Username))
            {
                throw new Exception("用户名不能为空");
            }
            if (string.IsNullOrEmpty(inModel.Password))
            {
                throw new Exception("密码不能为空");
            }
            #endregion

            dynamic wherePart = new ExpandoObject();
            wherePart.Username = inModel.Username;
            wherePart.IsDelete = 0;

            if (loginBll.Login(wherePart) && inModel.Password == "1")
            {
                //保存Session
                Session["UserName"] = inModel.Username;

                actionResult = new JsonResult()
                {
                    Data = new {
                        Message = StandardMessage.Success
                    },
                    JsonRequestBehavior = JsonRequestBehavior.AllowGet
                };
            }
            else
            {
                actionResult = new JsonResult()
                {
                    Data = new {
                        Message = StandardMessage.Error
                    },
                    JsonRequestBehavior = JsonRequestBehavior.AllowGet
                };
            }

            return actionResult;
        }

        public ActionResult Exit()
        {
            Session.Clear();
            Session.Abandon();

            return RedirectToAction("Index", "Login");
        }
    }
}

Test.UI/Controllers/MenuTreeController.cs
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using Test.BLL;
using Test.Model;
using Test.UI.Common;

namespace Test.UI.Controllers
{
    public class MenuTreeController : Controller
    {
        AreaBll areaBll = new AreaBll();
        CityBll cityBll = new CityBll();

        [MyAuthorize]
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 根据IsDelete获取大区列表
        /// </summary>
        /// <returns></returns>
        public ActionResult GetTreeByIsDelete()
        {
            var actionResult = default(ActionResult);

            try
            {
                dynamic wherePart = new ExpandoObject();
                wherePart.IsDelete = 0;

                //获取大区列表
                List<Area> areaList = areaBll.GetListByIsDelete(wherePart);
                //获取城市列表
                List<City> cityList = cityBll.GetListByIsDelete(wherePart);

                string xml = string.Empty;
                if (areaList != null)
                {
                    //拼接树
                    xml = @"
                                <tree id='0'>
                                    <item text='全部' id='1' child='1' im0='folderClosed.gif' im1='folderClosed.gif' im2='folderClosed.gif' open='1'>
                                        {0}
                                    </item>
                                </tree>
                            ";

                    xml = string.Format(xml, GetTree.GetCityTree(areaList, cityList));

                    //actionResult = new ContentResult()
                    //{
                    //    Content = new JavaScriptSerializer().Serialize(new
                    //    {
                    //        Message = StandardMessage.Success,
                    //        XmlOfAreaTree = xml
                    //    })
                    //};

                    actionResult = new JsonResult()
                    {
                        Data = new
                        {
                            Message = StandardMessage.Success,
                            XmlOfAreaTree = xml
                        },
                        JsonRequestBehavior = JsonRequestBehavior.AllowGet
                    };
                }
                else
                {
                    actionResult = new ContentResult()
                    {
                        Content = new JavaScriptSerializer().Serialize(new
                        {
                            Message = StandardMessage.Error
                        })
                    };
                }
            }
            catch (Exception e)
            {
                actionResult = new ContentResult()
                {
                    Content = new JavaScriptSerializer().Serialize(new
                    {
                        Message = e.Message
                    })
                };
            }

            return actionResult;
        }
    }
}

Test.UI/Views/Login/Index.cshtml
@using Test.UI.Common
@{
    ViewBag.Title = "Index";
}

<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="~/Resource/Img/favicon.ico">
    <title>登录</title>
    <link href="~/Resource/Scripts/bootstrap-3.3.4-dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Resource/Css/signin.css" rel="stylesheet" />
    <script src="~/Resource/Scripts/ie-emulation-modes-warning.js"></script>
    <style type="text/css">
        .form-signin-heading {
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="container">
        <form class="form-signin">
            <h2 class="form-signin-heading">Welcome Back</h2>
            <label for="inputEmail" class="sr-only">用户名</label>
            <input type="email" id="inputEmail" class="form-control" placeholder="用户名" required autofocus>
            <label for="inputPassword" class="sr-only">密码</label>
            <input type="password" id="inputPassword" class="form-control" placeholder="密码" required>
            <div class="checkbox">
                <label>
                    <input type="checkbox" value="remember-me">
                    记住我
                </label>
            </div>
            <button id="btnLogin" class="btn btn-lg btn-primary btn-block" type="submit">登录</button>
        </form>
    </div>

    <!--JavaScript-->
    <script src="~/Resource/Scripts/jquery-2.1.1.js"></script>
    <script src="~/Resource/Scripts/bootstrap-3.3.4-dist/js/bootstrap.min.js"></script>
    <script src="~/Resource/Scripts/ie10-viewport-bug-workaround.js"></script>
    <script type="text/javascript">
        $(function () {
            //登录按钮
            $('#btnLogin').click(function () {
                ////非空验证
                var userName = $('#inputEmail').val();
                //if ($.trim(userName).length == 0) {
                //    alert('用户名不能为空');
                //    return;
                //}
                var pwd = $('#inputPassword').val();
                //if ($.trim(pwd).length == 0) {
                //    alert('密码不能为空');
                //    return;
                //}

                $.getJSON('/Login/Login?random=' + Math.random(), { Username: userName, Password: pwd }, function (_jsonData) {
                    if (_jsonData.Message == '@StandardMessage.Success') {
                        window.location.href = '@Url.Action("Index", "MenuTree")';
                    } else {
                        alert('用户名或密码错误');
                    }
                });
            });
        });
    </script>
</body>
</html>