Test.UI/Controllers/BbsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Test.BLL;
using Test.Model;

namespace Test.UI.Controllers
{
    public class BbsController : Controller
    {
        BBSBll bbsBll = new BBSBll();

        public ActionResult Index()
        {
            List<BBS> list = bbsBll.GetList();
            ViewBag.list = list;
            return View();
        }

        /// <summary>
        /// 添加评论
        /// </summary>
        /// <param name="bbs">评论对象</param>
        /// <returns>Json</returns>
        public ActionResult Add(BBS bbs)
        {
            JsonResult j = new JsonResult()
            {
                Data = "no"
            };
            j.JsonRequestBehavior = JsonRequestBehavior.AllowGet;

            string content = bbs.Content;

            //评论为空
            if (string.IsNullOrEmpty(content))
            {
                j.Data = "isNull";
                return j;
            }

            content = HttpUtility.UrlDecode(content);
            bbs.Content = content;
            
            bool r = bbsBll.Add(bbs);

            if (r)
            {
                j.Data = "ok";
            }
            return j;
        }

        /// <summary>
        /// 删除评论
        /// </summary>
        /// <param name="id">评论id</param>
        /// <returns>Json</returns>
        public ActionResult Delete(int id)
        {
            string result = "no";
            bool r = bbsBll.Delete(id);

            if (r)
            {
                result = "ok";
            }

            JsonResult j = new JsonResult() 
            {
                Data = result
            };
            j.JsonRequestBehavior = JsonRequestBehavior.AllowGet;

            return j;
        }
    }
}

Test.UI/Views/Bbs/Index.cshtml
@model List<Test.Model.BBS>
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Index</title>
    <script src="~/Resource/Scripts/jquery-2.1.1.js"></script>
    <script src="~/UM/third-party/jquery.min.js"></script>
    <link href="~/UM/themes/default/css/umeditor.css" rel="stylesheet" />
    <script src="~/UM/umeditor.config.js"></script>
    <script src="~/UM/umeditor.js"></script>
    <script type="text/javascript">
        $(function () {
            //实例化编辑器
            var um = UM.getEditor('myEditor');

            //发表评论
            $('#umpl').click(function () {
                var arr = [];
                arr.push(um.getContent());
                alert(arr);

                $.getJSON('@Url.Action("Add", "Bbs")', { Content: escape(arr.toString()) }, function (_jsonData) {
                    if (_jsonData == 'ok') {
                        alert('评论成功');
                        location.href = '@Url.Action("Index", "Bbs")';
                    } else if (_jsonData == 'isNull') {
                        alert('请输入评论内容');
                    }
                    else {
                        alert('评论失败');
                    }
                });
            });
        });

        //删除
        function Delete(aLink) {
            //确认删除
            if (!confirm('确定要删除么？')) {
                return;
            }

            //获取评论id
            var id = $(aLink).attr('id');

            //发送请求
            $.getJSON('@Url.Action("Delete", "Bbs")', { id: id }, function (_jsonDate) {
                if (_jsonDate == 'ok') {
                    alert('删除成功');
                    location.href = '@Url.Action("Index", "Bbs")';
                } else {
                    alert('删除失败');
                }
            });
        }
    </script>
    <style type="text/css">
        #list a {
            text-decoration: none;
            font-size: 14px;
            color: grey;
        }
    </style>
</head>
<body>
    <div>
        <table border="1">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Content</th>
                    <th>操作</th>
                </tr>
            </thead>
            <tbody id="list">
                @foreach (var item in ViewBag.list)
                {
                    <tr>
                        <td>@item.Id</td>
                        <td>@item.Content</td>
                        <td style="text-align: center">
                            <a id="@item.Id" href="javascript:void(0)" onclick="Delete(this)">删除</a>
                        </td>
                    </tr> 
                }
            </tbody>
        </table>
        <br />
        <!--style给定宽度可以影响编辑器的最终宽度-->
        <script type="text/plain" id="myEditor" style="width: 1000px; height: 200px;">
            <p>这里我可以写一些输入提示</p>
        </script>
        @*<div class="clear"></div>*@
        <input type="button" id="umpl" value="发表评论" />
        <br />
        <br />
        <br />
    </div>
</body>
</html>